In [476]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import os
print(os.path.abspath('column_info.txt'))


pd.set_option('display.max_columns', None)   
pd.set_option('display.width', None)        
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

import numpy as np
np.set_printoptions(threshold=np.inf)

c:\Users\91701\OneDrive\Documents\PulseGuard AI – Intelligent Blood Pressure Prediction System hackthon 2026\Eda\column_info.txt


In [477]:
data = pd.read_csv(r'C:\Users\91701\OneDrive\Documents\PulseGuard AI – Intelligent Blood Pressure Prediction System hackthon 2026\patient_data.csv')
print(data.head())
print('--------//--------')
print(data.tail())

        C    Age History Patient TakeMedication Severity BreathShortness  \
0    Male  18-34     Yes      No             No     Mild              No   
1  Female  18-34     Yes      No             No     Mild              No   
2    Male  35-50     Yes      No             No     Mild              No   
3  Female  35-50     Yes      No             No     Mild              No   
4    Male  51-64     Yes      No             No     Mild              No   

  VisualChanges NoseBleeding Whendiagnoused   Systolic Diastolic  \
0            No          No         <1 Year  111 - 120   81 - 90   
1            No          No         <1 Year  111 - 120   81 - 90   
2            No          No         <1 Year  111 - 120   81 - 90   
3            No          No         <1 Year  111 - 120   81 - 90   
4            No          No         <1 Year  111 - 120   81 - 90   

  ControlledDiet                  Stages  
0             No  HYPERTENSION (Stage-1)  
1             No  HYPERTENSION (Stage-1)  
2    

In [478]:
for col in data.columns:
    print(f"Column: {col}")
    print(data[col].unique())
    print("Number of unique values:", data[col].nunique())
    print("-----------")


Column: C
['Male' 'Female']
Number of unique values: 2
-----------
Column: Age
['18-34' '35-50' '51-64' '65+']
Number of unique values: 4
-----------
Column: History
['Yes' 'No']
Number of unique values: 2
-----------
Column: Patient
['No' 'Yes']
Number of unique values: 2
-----------
Column: TakeMedication
['No' 'Yes ' 'Yes']
Number of unique values: 3
-----------
Column: Severity
['Mild' 'Sever' 'Moderate']
Number of unique values: 3
-----------
Column: BreathShortness
['No' 'Yes']
Number of unique values: 2
-----------
Column: VisualChanges
['No' 'Yes']
Number of unique values: 2
-----------
Column: NoseBleeding
['No ' 'No' 'Yes']
Number of unique values: 3
-----------
Column: Whendiagnoused
['<1 Year' '1 - 5 Years' '>5 Years']
Number of unique values: 3
-----------
Column: Systolic
['111 - 120' '121- 130' '130+' '100+' '121 - 130']
Number of unique values: 5
-----------
Column: Diastolic
['81 - 90' '91 - 100' '100+' '130+' '70 - 80']
Number of unique values: 5
-----------
Column: C

In [479]:
# Remove leading/trailing spaces
data = data.apply(lambda x: x.str.strip() if x.dtype == "object" else x)

# Convert everything to lowercase (very important)
data = data.apply(lambda x: x.str.lower() if x.dtype == "object" else x)

# Normalize dash formatting
for col in ['Age', 'Systolic', 'Diastolic']:
    if col in data.columns:
        data[col] = data[col].str.replace('-', ' - ')
        data[col] = data[col].str.replace('  ', ' ')

In [480]:
data['Stages'] = data['Stages'].replace({'hypertensive crisi': 'hypertensive crisis'})
data['Stages'] = data['Stages'].str.rstrip('.')


In [481]:
data.columns

Index(['C', 'Age', 'History', 'Patient', 'TakeMedication', 'Severity',
       'BreathShortness', 'VisualChanges', 'NoseBleeding', 'Whendiagnoused',
       'Systolic', 'Diastolic', 'ControlledDiet', 'Stages'],
      dtype='object')

In [482]:
data.rename(columns={'C':'Gender'}, inplace=True)

for col in data.columns:
    print(f"Column: {col}")
    print(data[col].unique())
    print("Number of unique values:", data[col].nunique())
    print("-----------")


Column: Gender
['male' 'female']
Number of unique values: 2
-----------
Column: Age
['18 - 34' '35 - 50' '51 - 64' '65+']
Number of unique values: 4
-----------
Column: History
['yes' 'no']
Number of unique values: 2
-----------
Column: Patient
['no' 'yes']
Number of unique values: 2
-----------
Column: TakeMedication
['no' 'yes']
Number of unique values: 2
-----------
Column: Severity
['mild' 'sever' 'moderate']
Number of unique values: 3
-----------
Column: BreathShortness
['no' 'yes']
Number of unique values: 2
-----------
Column: VisualChanges
['no' 'yes']
Number of unique values: 2
-----------
Column: NoseBleeding
['no' 'yes']
Number of unique values: 2
-----------
Column: Whendiagnoused
['<1 year' '1 - 5 years' '>5 years']
Number of unique values: 3
-----------
Column: Systolic
['111 - 120' '121 - 130' '130+' '100+']
Number of unique values: 4
-----------
Column: Diastolic
['81 - 90' '91 - 100' '100+' '130+' '70 - 80']
Number of unique values: 5
-----------
Column: ControlledDiet

In [483]:
with open('column_info.txt', 'w') as f:
    for col in data.columns:
        f.write(f"Column: {col}\n")
        unique_vals = data[col].unique().tolist()
        for val in unique_vals:
            f.write(f"  - {val}\n")
        f.write(f"Number of unique values: {len(unique_vals)}\n")
        f.write("-----------\n")

print("Done! Check column_info.txt")

Done! Check column_info.txt


In [484]:
data.isnull().sum()

Gender             0
Age                0
History            0
Patient            0
TakeMedication     0
Severity           0
BreathShortness    0
VisualChanges      0
NoseBleeding       0
Whendiagnoused     0
Systolic           0
Diastolic          0
ControlledDiet     0
Stages             0
dtype: int64

In [485]:
nominal_features=['Gender', 'History', 'Patient', 'TakeMedication', 'BreathShortness', 'VisualChanges', 'NoseBleeding', 'ControlledDiet']
ordinal_features=[f for f in data.columns if f not in nominal_features]
ordinal_features.remove('Stages')
print (nominal_features)
print(ordinal_features)

['Gender', 'History', 'Patient', 'TakeMedication', 'BreathShortness', 'VisualChanges', 'NoseBleeding', 'ControlledDiet']
['Age', 'Severity', 'Whendiagnoused', 'Systolic', 'Diastolic']


In [486]:

# Encode Nominal Features


for col in nominal_features:
    
    if set(data[col].unique()) == {'yes', 'no'}:
        data[col] = data[col].map({'no': 0, 'yes': 1})
    
    elif col == 'Gender':
        data[col] = data[col].map({'male': 0, 'female': 1})


# Encode Ordinal Features


data['Age'] = data['Age'].map({
    '18 - 34': 1,
    '35 - 50': 2,
    '51 - 64': 3,
    '65+': 4
})

data['Severity'] = data['Severity'].replace({
    'mild': 0,
    'moderate': 1,
    'sever': 2
})

data['Whendiagnoused'] = data['Whendiagnoused'].map({
    '<1 year': 1,
    '1 - 5 years': 2,
    '>5 years': 3
})

data['Systolic'] = data['Systolic'].map({
    '100+': 0,
    '111 - 120': 1,
    '121 - 130': 2,
    '130+': 3
})


data['Diastolic'] = data['Diastolic'].map({
    '70 - 80': 0,
    '81 - 90': 1,
    '91 - 100': 2,
    '100+': 3,
    '130+': 4
})



# Encode Target

data['Stages'] = data['Stages'].map({
    'normal': 0,
    'hypertension (stage-1)': 1,
    'hypertension (stage-2)': 2,
    'hypertensive crisis': 3
})


C:\Users\91701\AppData\Local\Temp\ipykernel_1744\2364453786.py:23: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Severity'] = data['Severity'].replace({


In [487]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
data[ordinal_features]= scaler.fit_transform(data[ordinal_features])


In [488]:
print(data.isnull().sum())

Gender             0
Age                0
History            0
Patient            0
TakeMedication     0
Severity           0
BreathShortness    0
VisualChanges      0
NoseBleeding       0
Whendiagnoused     0
Systolic           0
Diastolic          0
ControlledDiet     0
Stages             0
dtype: int64


In [489]:
from sklearn.model_selection import train_test_split
x= data.drop('Stages', axis=1)
y=data['Stages']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [490]:
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy={}


In [491]:
#Logistic Regression

logreg = LogisticRegression()
logreg.fit(x_train, y_train)
y_pred = logreg.predict(x_test)
print("Logistic Regression:\n ")
print(f"Accuracy: {accuracy_score(y_test, y_pred)*100:.2f} %")
print("Classification Report: \n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
accuracy={'Logistic Regression' : accuracy_score(y_test, y_pred) }


Logistic Regression:
 
Accuracy: 97.26 %
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        60
           1       1.00      1.00      1.00       139
           2       0.99      0.93      0.96       120
           3       0.83      0.98      0.90        46

    accuracy                           0.97       365
   macro avg       0.96      0.98      0.96       365
weighted avg       0.98      0.97      0.97       365

Confusion Matrix:
 [[ 60   0   0   0]
 [  0 139   0   0]
 [  0   0 111   9]
 [  0   0   1  45]]


In [492]:
#Decision Tree

decisionTree=DecisionTreeClassifier()
decisionTree.fit(x_train, y_train)
y_pred = decisionTree.predict(x_test)
print("Decision Tree:\n")
print(f"Accuracy: {accuracy_score(y_test, y_pred)*100:.2f} %")
print("Classification Report: \n", classification_report(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
accuracy['Decision Tree']=accuracy_score(y_test, y_pred)


Decision Tree:

Accuracy: 100.00 %
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        60
           1       1.00      1.00      1.00       139
           2       1.00      1.00      1.00       120
           3       1.00      1.00      1.00        46

    accuracy                           1.00       365
   macro avg       1.00      1.00      1.00       365
weighted avg       1.00      1.00      1.00       365

Confusion Matrix: 
 [[ 60   0   0   0]
 [  0 139   0   0]
 [  0   0 120   0]
 [  0   0   0  46]]


In [493]:
#Random Forest

randomforest=RandomForestClassifier()
randomforest.fit(x_train, y_train)
y_pred = randomforest.predict(x_test)
print("Random Forest:\n")
print(f"Accuracy: {accuracy_score(y_test, y_pred)*100:.2f} %")
print("Classification Report: \n", classification_report(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
accuracy ['Random Forest' ]=accuracy_score(y_test, y_pred)


Random Forest:

Accuracy: 100.00 %
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        60
           1       1.00      1.00      1.00       139
           2       1.00      1.00      1.00       120
           3       1.00      1.00      1.00        46

    accuracy                           1.00       365
   macro avg       1.00      1.00      1.00       365
weighted avg       1.00      1.00      1.00       365

Confusion Matrix: 
 [[ 60   0   0   0]
 [  0 139   0   0]
 [  0   0 120   0]
 [  0   0   0  46]]


In [494]:
#Support Vector Machine

svm=SVC()
svm.fit(x_train, y_train)
y_pred = svm.predict(x_test)
print("Support Vector Machine:\n")
print(f"Accuracy: {accuracy_score(y_test, y_pred)*100:.2f} %")
print("Classification Report: \n", classification_report(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
accuracy['SVM' ]=accuracy_score(y_test, y_pred)



Support Vector Machine:

Accuracy: 98.90 %
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        60
           1       1.00      1.00      1.00       139
           2       1.00      0.97      0.98       120
           3       0.92      1.00      0.96        46

    accuracy                           0.99       365
   macro avg       0.98      0.99      0.99       365
weighted avg       0.99      0.99      0.99       365

Confusion Matrix: 
 [[ 60   0   0   0]
 [  0 139   0   0]
 [  0   0 116   4]
 [  0   0   0  46]]


In [495]:
#k nearest neighbors - KNN
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
print("K Nearest Neighbors:\n")
print(f"Accuracy: {accuracy_score(y_test, y_pred)*100:.2f} %")
print("Classification Report: \n", classification_report(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
accuracy['KNN']=accuracy_score(y_test, y_pred)


K Nearest Neighbors:

Accuracy: 94.25 %
Classification Report: 
               precision    recall  f1-score   support

           0       0.83      1.00      0.91        60
           1       1.00      0.91      0.95       139
           2       0.95      0.97      0.96       120
           3       0.93      0.87      0.90        46

    accuracy                           0.94       365
   macro avg       0.93      0.94      0.93       365
weighted avg       0.95      0.94      0.94       365

Confusion Matrix: 
 [[ 60   0   0   0]
 [ 12 127   0   0]
 [  0   0 117   3]
 [  0   0   6  40]]


In [496]:
#Ridge Classifier 

RC=RidgeClassifier()
RC.fit(x_train, y_train)
y_pred = RC.predict(x_test)
print("Ridge Classifier:\n")
print(f"Accuracy: {accuracy_score(y_test, y_pred)*100:.2f} %")
print("Classification Report: \n", classification_report(y_test, y_pred))   
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
accuracy['Ridge Classifier']=accuracy_score(y_test, y_pred)



Ridge Classifier:

Accuracy: 96.44 %
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        60
           1       1.00      1.00      1.00       139
           2       0.97      0.93      0.94       120
           3       0.82      0.91      0.87        46

    accuracy                           0.96       365
   macro avg       0.95      0.96      0.95       365
weighted avg       0.97      0.96      0.96       365

Confusion Matrix: 
 [[ 60   0   0   0]
 [  0 139   0   0]
 [  0   0 111   9]
 [  0   0   4  42]]


In [497]:
#Gaussian Naive Bayes

GNB=GaussianNB()
GNB.fit(x_train, y_train)
y_pred = GNB.predict(x_test)
print("Gaussian Naive Bayes:\n")
print(f"Accuracy: {accuracy_score(y_test, y_pred)*100:.2f} %")
print("Classification Report: \n", classification_report(y_test, y_pred))
print("Confusion Matrix: \n", confusion_matrix(y_test, y_pred))
accuracy['Gaussian Naive Bayes']=accuracy_score(y_test, y_pred)


Gaussian Naive Bayes:

Accuracy: 89.04 %
Classification Report: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        60
           1       1.00      1.00      1.00       139
           2       1.00      0.67      0.80       120
           3       0.53      1.00      0.70        46

    accuracy                           0.89       365
   macro avg       0.88      0.92      0.87       365
weighted avg       0.94      0.89      0.90       365

Confusion Matrix: 
 [[ 60   0   0   0]
 [  0 139   0   0]
 [  0   0  80  40]
 [  0   0   0  46]]


In [498]:
#Model selection and overfitting analysis
'''
Logistic Regression: 97.26 %
Decision Tree: 100 %
Random Forest: 100 %
Support Vector Machine: 98.90%
K Nearest Neighbors: 94.25 % %
Ridge Classifier: 96.44 %
Gaussian Naive Bayes: 89.04 %
'''


'\nLogistic Regression: 97.26 %\nDecision Tree: 100 %\nRandom Forest: 100 %\nSupport Vector Machine: 98.90%\nK Nearest Neighbors: 94.25 % %\nRidge Classifier: 96.44 %\nGaussian Naive Bayes: 89.04 %\n'

In [ ]:
'''
Logistic regression model looks good with 97.26% accuracy

Key Performance Indicators: 
● Overall Accuracy: 97.26% - Excellent classification performance 
● Macro Average F1-Score: 0.96 - Balanced performance across all classes 
● Weighted Average F1-Score: 0.97 - Strong overall classification quality 
● Crisis Recall: 100% - No missed emergency cases

 Stage-2 Precision: 100% - No false Stage-2 diagnoses 

'''

'\nLogistic regression model looks good with 97.26% accuracy\n\nKey Performance Indicators: \n● Overall Accuracy: 97.26% - Excellent classification performance \n● Macro Average F1-Score: 0.96 - Balanced performance across all classes \n● Weighted Average F1-Score: 0.97 - Strong overall classification quality \n● Crisis Recall: 100% - No missed emergency cases\n\n'

In [500]:
import joblib

#save modell
joblib.dump(logreg, 'logistic_regression_model.pkl')
print("Model saved!!!  as - logistic_regression_model.pkl")

Model saved!!!  as - logistic_regression_model.pkl
